name: proyecto_nexo
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.5
  - pandas=2.2.2
  - numpy=1.26.4
  - scikit-learn=1.5.1
  - scikit-surprise=1.1.4
  - matplotlib=3.9.2
  - seaborn=0.13.2
  - joblib=1.4.2
  - uvicorn=0.30.6
  - typer=0.12.5
  - starlette=0.38.4
  - jupyterlab=4.0.5
  - ipykernel=6.29.5
  - plotly=5.24.0
  - pillow=10.4.0
  - bzip2=1.0.8
  - zlib=1.3.1
  - xz=5.2.6
  - readline=8.2
  - libsqlite=3.46.0
  - libgcc-ng=14.1.0
  - zeromq=4.3.5
  - pyyaml=6.0.2
  - setuptools=72.2.0
  - pip
  - pip:
      - fastapi==0.113.0
      - fastapi-cli==0.0.5
      - dnspython==2.6.1
      - email-validator==2.2.0
      - uvloop==0.20.0
      - websockets==13.0.1
      - httpx==0.27.2
      - tenacity==9.0.0
      - python-dotenv==1.0.1
      - pydantic==2.8.2